include:
  - project: 'docker/process-webhooks'
    file: '/gitlab/deploy.yml'

variables:
  PROJECT_TO_BE_DEPLOYED: 'docker/parallel-corpus-search'

image: docker:stable

services:
- docker:stable-dind


stages:
  - webservice
  - deploy

webservice:
  stage: webservice
  needs: []
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - export REPO_NAME=$CI_REGISTRY_IMAGE/webservice
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_NAME
    - export DOCKER_PATH=web/docker/dockerfile
    - docker build -f $DOCKER_PATH --tag $IMAGE_NAME .
    - docker push $IMAGE_NAME


deploy:
  stage: deploy
  extends:
    .default-deploy
