image: docker:stable

services:
- docker:stable-dind

before_script:
- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - elasticsearch
  - webservice

elasticsearch:
  stage: elasticsearch
  script:
    - sysctl -w vm.max_map_count=262144
    - export REPO_NAME=$CI_REGISTRY_IMAGE/elasticsearch
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_NAME
    - export DOCKER_PATH=elasticsearch_static_data/dockerfile
    - docker build -f $DOCKER_PATH --tag $IMAGE_NAME --tag $REPO_NAME:$CI_COMMIT_SHA .
    - docker push $REPO_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME

webservice:

  stage: webservice
  needs: []
  script:
    - export REPO_NAME=$CI_REGISTRY_IMAGE/webservice
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_NAME
    - export DOCKER_PATH=web/docker/dockerfile
    - docker build -f $DOCKER_PATH --tag $IMAGE_NAME --tag $REPO_NAME:$CI_COMMIT_SHA .
    - docker push $REPO_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME
