stages:
  - build

build:
  image: docker:stable
  services:
    - docker:stable-dind
  before_script:
    - apk add --no-cache py-pip python3
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - export DATETAG=$(date +%Y%m%d-%H%M%S)
  stage: build
  script:
    - sysctl -w vm.max_map_count=262144
    - docker build -f elasticsearch_static_data/dockerfile --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:$DATETAG --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$DATETAG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
