# This docker-compose is used only in local for development
version: '3'
services:
  es01:
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    image: elasticsearch-static
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - elastic

  ui:
    image: elastichq/elasticsearch-hq
    ports:
      - 6000:5000
    networks:
      - elastic

  web-service:
    image: parallel-corpus-search
    ports:
      - 8000:8000
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
