FROM python:3.12.2-slim-bullseye

COPY web/requirements.txt /srv/
RUN pip install -r srv/requirements.txt

COPY web/docker/entrypoint.sh /srv/
COPY web/*.py /srv/

ENTRYPOINT srv/entrypoint.sh
RUN bash
